### ISSUE TITLE
News about dothost

### ISSUE THREAD

**Issue by thiagoandrade01** [jwilk/dothost#2]
Hi Jakub Wilk,
How are you doing?
I'm Thiago Andrade and i packaged dothost in Debian.
Dothost is still in NEW[1].
I upgraded the manpage with some examples and more functions to the program.
If you want to add this in a new release, i am making my patch available with the modifications.

Thanks for your work.
Regards.
Andrade

[1] https://ftp-master.debian.org/new/dothost_0.2-1.html

[010_added-information-manpage.patch.tar.gz](https://github.com/jwilk/dothost/files/3772483/010_added-information-manpage.patch.tar.gz)

**Comment by jwilk** [comment]
> I'm Thiago Andrade and i packaged dothost in Debian.

Thanks for letting me know.
I've added distro links to the [home page](http://jwilk.net/software/dothost).

> I upgraded the manpage with some examples and more functions to the program.

I've turned your patch into PR #3.
